# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2025.M.179
# Date: 2025-07-17 15:46

# Copyright (C) 2013 - 2025 Efinix Inc. All rights reserved.

# Device: Ti375N1156
# Project: efx_ethernet_1g_exp
# Timing Model: C4 (final)

# Oscillator Constraints
########################
#create_clock -period 12.5 -name osc_CLKOUT [get_ports {osc_CLKOUT}]

# PLL Constraints
#################
#create_clock -period 10.000 -name pll_inst1_CLKOUT0 [get_ports {pll_inst1_CLKOUT0}]
create_clock -period 20.000 -name APB_CLK [get_ports {APB_CLK}]
create_clock -period 20.000 -name INIT_CLK [get_ports {INIT_CLK}]

# GPIO Constraints
####################

# JTAG Constraints
####################
create_clock -period 100 -name jtag_vio_TCK [get_ports {jtag_vio_TCK}]
set_output_delay -clock jtag_vio_TCK -max 2.452 [get_ports {jtag_vio_TDO}]
set_output_delay -clock jtag_vio_TCK -min 1.244 [get_ports {jtag_vio_TDO}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.917 [get_ports {jtag_vio_CAPTURE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.469 [get_ports {jtag_vio_CAPTURE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 1.488 [get_ports {jtag_vio_RESET}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.955 [get_ports {jtag_vio_RESET}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.878 [get_ports {jtag_vio_SEL}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.507 [get_ports {jtag_vio_SEL}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.853 [get_ports {jtag_vio_UPDATE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.452 [get_ports {jtag_vio_UPDATE}]
set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.985 [get_ports {jtag_vio_SHIFT}]
set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.497 [get_ports {jtag_vio_SHIFT}]
#set_input_delay -clock_fall -clock jtag_vio_TCK -max 1.644 [get_ports {jtag_vio_DRCK}]
#set_input_delay -clock_fall -clock jtag_vio_TCK -min 1.001 [get_ports {jtag_vio_DRCK}]
# JTAG Constraints (extra... not used by current Efinity debug tools)
# create_clock -period <USER_PERIOD> -name jtag_vio_DRCK [get_ports {jtag_vio_DRCK}]
# set_input_delay -clock_fall -clock jtag_vio_TCK -max 0.864 [get_ports {jtag_vio_RUNTEST}]
# set_input_delay -clock_fall -clock jtag_vio_TCK -min 0.475 [get_ports {jtag_vio_RUNTEST}]
# Create separate clock groups for JTAG clocks. Remove DRCK clock from the list below if it is not defined.
# set_clock_groups -asynchronous -group {jtag_vio_TCK jtag_vio_DRCK}

# Ethernet SGMII Constraints
create_clock -period 6.4 -name L0_1gbe_clk [get_ports {L0_1gbe_clk}]
#create_clock -period 3.2 -name L0_1gbe_clk_x2 [get_ports {L0_1gbe_clk_x2}]
create_clock -period 6.4 -name L3_1gbe_clk [get_ports {L3_1gbe_clk}]
#create_clock -period 3.2 -name L3_1gbe_clk_x2 [get_ports {L3_1gbe_clk_x2}]
set_clock_groups -async -group jtag_vio_TCK \
                        -group APB_CLK \
                        -group INIT_CLK \
						-group L0_1gbe_clk \
						-group L3_1gbe_clk 
						
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PADDR[*]}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PSEL}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PENABLE}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PWRITE}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_USER_APB_PWDATA[*]}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min -0.245 [get_ports {Q1_SGMII_USER_APB_RESET_N}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 0.531 [get_ports {Q1_USER_APB_PADDR[*]}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 0.708 [get_ports {Q1_USER_APB_PSEL}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 0.418 [get_ports {Q1_USER_APB_PENABLE}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 0.392 [get_ports {Q1_USER_APB_PWRITE}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 0.543 [get_ports {Q1_USER_APB_PWDATA[*]}]
set_output_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 1.983 [get_ports {Q1_SGMII_USER_APB_RESET_N}]

set_input_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 2.152 [get_ports {Q1_USER_APB_PRDATA[*]}]
set_input_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min 0.245 [get_ports {Q1_USER_APB_PRDATA[*]}]
set_input_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -max 1.951 [get_ports {Q1_USER_APB_PREADY}]
set_input_delay -clock APB_CLK -reference_pin [get_ports {APB_CLK~CLKOUT~466~244}] -min 0.245 [get_ports {Q1_USER_APB_PREADY}]


###########################
#          L0             #
###########################
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -min -0.245 [get_ports {L0_GMII_TXD[*]}]
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -min -0.245 [get_ports {L0_GMII_TX_EN[*]}]
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -min -0.245 [get_ports {L0_GMII_TX_ER[*]}]
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -max 0.991 [get_ports {L0_GMII_TXD[*]}]
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -max 0.991 [get_ports {L0_GMII_TX_EN[*]}]
set_output_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~466~243}] -max 0.991 [get_ports {L0_GMII_TX_ER[*]}]

set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_GMII_RXD[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_GMII_RXD[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_GMII_RX_DV[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_GMII_RX_DV[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_GMII_RX_ER[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_GMII_RX_ER[*]}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_SYNC_STATUS}]
set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_SYNC_STATUS}]

#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_CTC_ERR}]
#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_CTC_ERR}]
#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_TX_ACTIVITY}]
#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_TX_ACTIVITY}]
#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -max 1.572 [get_ports {L0_RX_ACTIVITY}]
#set_input_delay -clock L0_1gbe_clk -reference_pin [get_ports {L0_1gbe_clk~CLKOUT~465~243}] -min 0.245 [get_ports {L0_RX_ACTIVITY}]

###########################
#          L3             #
###########################
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -min -0.245 [get_ports {L3_GMII_TXD[*]}]
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -min -0.245 [get_ports {L3_GMII_TX_EN[*]}]
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -min -0.245 [get_ports {L3_GMII_TX_ER[*]}]
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -max 0.991 [get_ports {L3_GMII_TXD[*]}]
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -max 0.991 [get_ports {L3_GMII_TX_EN[*]}]
set_output_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~466~403}] -max 0.991 [get_ports {L3_GMII_TX_ER[*]}]

set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_GMII_RXD[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_GMII_RXD[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_GMII_RX_DV[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_GMII_RX_DV[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_GMII_RX_ER[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_GMII_RX_ER[*]}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_SYNC_STATUS}]
set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_SYNC_STATUS}]

#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_CTC_ERR}]
#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_CTC_ERR}]
#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_TX_ACTIVITY}]
#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_TX_ACTIVITY}]
#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -max 1.572 [get_ports {L3_RX_ACTIVITY}]
#set_input_delay -clock L3_1gbe_clk -reference_pin [get_ports {L3_1gbe_clk~CLKOUT~465~403}] -min 0.245 [get_ports {L3_RX_ACTIVITY}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 3.726> [get_ports {pll_inst1_CLKOUT0}]
# set_clock_latency -source -hold <board_min + 2.045> [get_ports {pll_inst1_CLKOUT0}]
# set_clock_latency -source -setup <board_max + 3.726> [get_ports {APB_CLK}]
# set_clock_latency -source -hold <board_min + 2.045> [get_ports {APB_CLK}]
# set_clock_latency -source -setup <board_max + 3.726> [get_ports {INIT_CLK}]
# set_clock_latency -source -hold <board_min + 2.045> [get_ports {INIT_CLK}]
